# -*- coding: utf-8 -*-
"""Week-1(I)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sn8jK-XhdBreYjPudLVR8X8lX4RAvuMI

**TASK-1**
"""

print("Welcome to InternNova Week 1 Assignment")

name = input("Enter your Name: ")
college = input("Enter your College Name: ")
branch = input("Enter your Branch: ")

print("\n--- Student Information ---")
print("Name:", name)
print("College:", college)
print("Branch:", branch)

"""**TASK-2**"""

age = 21
percentage = 85.5
name = "Ananya"
is_student = True

print("Age:", age)
print("Data Type:", type(age))

print("\nPercentage:", percentage)
print("Data Type:", type(percentage))

print("\nName:", name)
print("Data Type:", type(name))

print("\nIs Student:", is_student)
print("Data Type:", type(is_student))

"""**TASK-3**"""

num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))

print("\n--- Calculator ---")

print("Addition:", num1 + num2)
print("Subtraction:", num1 - num2)
print("Multiplication:", num1 * num2)

if num2 != 0:
    print("Division:", num1 / num2)
    print("Modulus:", num1 % num2)
else:
    print("Division: Cannot divide by zero")
    print("Modulus: Cannot divide by zero")

"""**TASK-4**"""

marks = float(input("Enter your marks: "))

if marks >= 90:
    grade = "A"
elif marks >= 75:
    grade = "B"
elif marks >= 60:
    grade = "C"
else:
    grade = "Fail"

print("Grade:", grade)

"""**TASK-5**

****5.1***
"""

print("Numbers from 1 to 20:")

for i in range(1, 21):
    print(i)

"""***5.2***"""

num = int(input("Enter a number: "))

print("\nMultiplication Table of", num)

for i in range(1, 11):
    print(num, "x", i, "=", num * i)

"""***5.3***"""

num = 2

print("Even numbers from 1 to 50:")

while num <= 50:
    print(num)
    num += 2

"""**TASK-6**"""

def square(number):
    return number * number


def average(a, b, c):
    return (a + b + c) / 3


num = float(input("Enter a number to find its square: "))

a = float(input("Enter first number: "))
b = float(input("Enter second number: "))
c = float(input("Enter third number: "))

print("Square:", square(num))
print("Average:", average(a, b, c))

"""**TASK-7**"""

# String Operations

text = "Python Programming"

print("Original String:", text)
print("Uppercase:", text.upper())
print("Lowercase:", text.lower())
print("Replace:", text.replace("Python", "Data"))
print("Position of Programming:", text.find("Programming"))


# List Operations

fruits = ["Apple", "Banana", "Mango"]

print("\nOriginal List:", fruits)

fruits.append("Orange")
print("After append:", fruits)

fruits.remove("Banana")
print("After remove:", fruits)

fruits.sort()
print("After sort:", fruits)


# Tuple

student_tuple = ("Ananya", 21, "CSE")

print("\nTuple:", student_tuple)
print("First element:", student_tuple[0])
print("Second element:", student_tuple[1])


# Dictionary

student = {
    "Name": "Ananya",
    "Age": 21,
    "Branch": "CSE",
    "College": "Bennett University"
}

print("\nStudent Dictionary:", student)
print("Student Name:", student["Name"])
print("Branch:", student["Branch"])


# Set

subjects = {"Python", "Java", "SQL"}

print("\nOriginal Set:", subjects)

subjects.add("C++")
print("After add:", subjects)

subjects.remove("Java")
print("After remove:", subjects)

"""**TASK-8**"""

file = open("introduction.txt", "w")

file.write("Hello, my name is Ananya.\n")
file.write("I am pursuing B.Tech in Computer Science Engineering.\n")
file.write("I am currently learning Python and Data Analytics.\n")

file.close()

file = open("introduction.txt", "r")

content = file.read()

print("File Contents:")
print(content)

file.close()

"""**TASK-9**"""

students = []


def add_student():
    name = input("Enter student name: ")
    age = int(input("Enter student age: "))
    branch = input("Enter student branch: ")
    college = input("Enter college name: ")

    student = {
        "name": name,
        "age": age,
        "branch": branch,
        "college": college
    }

    students.append(student)

    print("Student added successfully!")


def display_students():
    if len(students) == 0:
        print("No student records found.")
    else:
        print("\n--- Student Records ---")

        for student in students:
            print("Name:", student["name"])
            print("Age:", student["age"])
            print("Branch:", student["branch"])
            print("College:", student["college"])
            print("----------------------")


def search_student():
    name = input("Enter student name to search: ")

    found = False

    for student in students:
        if student["name"].lower() == name.lower():
            print("\nStudent Found!")
            print("Name:", student["name"])
            print("Age:", student["age"])
            print("Branch:", student["branch"])
            print("College:", student["college"])
            found = True

    if not found:
        print("Student not found.")


def delete_student():
    name = input("Enter student name to delete: ")

    for student in students:
        if student["name"].lower() == name.lower():
            students.remove(student)
            print("Student deleted successfully!")
            return

    print("Student not found.")


while True:

    print("\n===== Student Record Management System =====")
    print("1. Add Student")
    print("2. Display All Students")
    print("3. Search Student")
    print("4. Delete Student")
    print("5. Exit")

    choice = input("Enter your choice: ")

    if choice == "1":
        add_student()

    elif choice == "2":
        display_students()

    elif choice == "3":
        search_student()

    elif choice == "4":
        delete_student()

    elif choice == "5":
        print("Thank you for using the system!")
        break

    else:
        print("Invalid choice. Please try again.")

